apiVersion: v1
data:
  mapRoles: "- rolearn: arn:aws:iam::949584776985:role/dev-NodeInstanceRole-1SETQF3F4VY44
    \n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n
    \   - system:nodes\n"
  mapUsers: "- userarn: arn:aws:iam::949584776985:user/htetnaing\n  username: htetnaing\n
    \ groups:\n    - system:masters\n- userarn: arn:aws:iam::949584776985:user/aiq-web-admin
    \n  username: aiq-web-admin \n  groups:\n    - aiq-web\n- userarn: arn:aws:iam::949584776985:user/aiq-web-view\n
    \ username: aiq-web-view\n  groups:\n    - aiq-web\n"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::949584776985:role/dev-NodeInstanceRole-1SETQF3F4VY44 \n  username: system:node:{{EC2PrivateDNSName}}\n  groups:\n    - system:bootstrappers\n    - system:nodes\n","mapUsers":"- userarn: arn:aws:iam::949584776985:user/htetnaing\n  username: htetnaing\n  groups:\n    - system:masters\n- userarn: arn:aws:iam::949584776985:user/aiq-web-admin \n  username: aiq-web-admin \n  groups:\n    - aiq-web\n- userarn: arn:aws:iam::949584776985:user/aiq-web-view\n  username: aiq-web-view\n  groups:\n    - aiq-web\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2019-02-01T08:38:12Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "10349"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b5d9d15e-25fc-11e9-929c-0e495319f628
