apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: gplus-prod-eks
  region: ap-southeast-2

vpc:
  id: "vpc-0dd6d3d2ffd7cffaf"
  cidr: "172.31.0.0/16"
  subnets:
    public:
      ap-southeast-2a: {id: "subnet-0528febfb503d0545"}
      ap-southeast-2b: {id: "subnet-05c26e19730a4533d"}
      ap-southeast-2c: {id: "subnet-07c93ba3c46325c70"}
  
    private:
      ap-southeast-2a: {id: "subnet-014d9aeecd49010d4"}
      ap-southeast-2b: {id: "subnet-0289b469af699ca4c"}
      ap-southeast-2c: {id: "subnet-0861d68941e76360b"}

nodeGroups:
  - name: prod-t3-meduim
    labels: {pool: prod-t3-medium}
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
    volumeSize: 30
    volumeType: gp2
    allowSSH: true
    sshPublicKeyPath: 'gplus-aws'
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
