apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: gplus-staging-eks
  region: ap-southeast-2

vpc:
  id: "vpc-06e5149bcdff1915e"
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ap-southeast-2a: {id: "subnet-07e9c61e1084ed65d"}
      ap-southeast-2b: {id: "subnet-0bd1c570d1d40abe6"}
      ap-southeast-2c: {id: "subnet-0c2f707a4abe714f0"}
  
    private:
      ap-southeast-2a: {id: "subnet-0cabb39fb233fe294"}
      ap-southeast-2b: {id: "subnet-04b72ddb39274f3dd"}
      ap-southeast-2c: {id: "subnet-0556fe9b4ea62f402"}

nodeGroups:
  - name: staging-t3-meduim
    labels: {pool: staging-t3-medium}
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
    volumeSize: 30
    volumeType: gp2
    allowSSH: true
    sshPublicKeyPath: 'gplus-aws'
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
