apiVersion: eksctl.io/v1alpha4
kind: ClusterConfig

metadata:
  name: staging-eks
  region: ap-southeast-2

vpc:
  id: "vpc-xxxx"
  cidr: "192.168.0.0/16"
  subnets:
    public:
      ap-southeast-2a: {id: "subnet-xxxx"}
      ap-southeast-2b: {id: "subnet-xxxx"}
      ap-southeast-2c: {id: "subnet-xxxx"}
  
    private:
      ap-southeast-2a: {id: "subnet-xxxx"}
      ap-southeast-2b: {id: "subnet-xxxx"}
      ap-southeast-2c: {id: "subnet-xxxx"}

nodeGroups:
  - name: staging-t3-meduim
    labels: {pool: staging-t3-medium}
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 20
    volumeSize: 30
    volumeType: gp2
    allowSSH: true
    sshPublicKeyPath: 'aws-staging-key'
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
