# Define persistent storage for Prometheus (PVC)
prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-pvc
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 10Gi

# Define persistent storage for Grafana (PVC)
grafana:
  # Set password for Grafana admin user
  adminPassword: gplus2020
  persistence:
    enabled: true
    storageClassName: gp2
    size: 10Gi

# Define persistent storage for Alertmanager (PVC)
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        metadata:
          name: alermanager-pvc
        spec:
          storageClassName: gp2
          resources:
            requests:
              storage: 10Gi